"""postgres_storage

Revision ID: e03e14f8ffdd
Revises: 0008_pi_tags_equipment_scope
Create Date: 2026-09-10 15:58:08.473513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e03e14f8ffdd'
down_revision: Union[str, None] = '0008_pi_tags_equipment_scope'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    is_sqlite = op.get_bind().dialect.name == "sqlite"
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite is used only by the migration fixture. Production PostgreSQL
    # keeps the original native partition for the rollback source; the next
    # revision creates the independent TimescaleDB hypertable.
    if is_sqlite:
        op.create_table(
            'pi_samples',
            sa.Column('tag_id', sa.Integer(), nullable=False),
            sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
            sa.Column('value_type', sa.String(length=50), nullable=False),
            sa.Column('value_double', sa.Float()),
            sa.Column('value_boolean', sa.Boolean()),
            sa.Column('value_text', sa.String()),
            sa.Column('good', sa.Boolean(), nullable=False),
            sa.Column('questionable', sa.Boolean(), nullable=False),
            sa.Column('substituted', sa.Boolean(), nullable=False),
            sa.Column('source_mode', sa.String(length=50), nullable=False),
            sa.PrimaryKeyConstraint('tag_id', 'ts'),
        )
    else:
        op.execute('''
        CREATE TABLE pi_samples (
            tag_id INTEGER NOT NULL,
            ts TIMESTAMP WITH TIME ZONE NOT NULL,
            value_type VARCHAR(50) NOT NULL,
            value_double FLOAT,
            value_boolean BOOLEAN,
            value_text VARCHAR,
            good BOOLEAN NOT NULL,
            questionable BOOLEAN NOT NULL,
            substituted BOOLEAN NOT NULL,
            source_mode VARCHAR(50) NOT NULL,
            PRIMARY KEY (tag_id, ts)
        ) PARTITION BY RANGE (ts);
    ''')
    # Create the first default partition for current month to avoid insertion errors
    if not is_sqlite:
        op.execute('''
            CREATE TABLE pi_samples_y2026m09 PARTITION OF pi_samples
            FOR VALUES FROM ('2026-09-01 00:00:00+00') TO ('2026-10-01 00:00:00+00');
        ''')
        op.execute('''
            CREATE TABLE pi_samples_y2026m10 PARTITION OF pi_samples
            FOR VALUES FROM ('2026-10-01 00:00:00+00') TO ('2026-11-01 00:00:00+00');
        ''')
    with op.batch_alter_table('pi_samples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pi_samples_tag_id'), ['tag_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pi_samples_ts'), ['ts'], unique=False)

    op.create_table('pi_backfill_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('target_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['pi_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pi_ingestion_coverage',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('range_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('range_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['pi_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pi_ingestion_coverage', schema=None) as batch_op:
        batch_op.create_index('ix_pi_ingestion_coverage_tag_range', ['tag_id', 'range_start', 'range_end'], unique=False)

    op.create_table('pi_ingestion_state',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('last_source_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_error_code', sa.String(length=255), nullable=True),
    sa.Column('last_error_message', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['pi_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_table('pi_tag_deletion_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['pi_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # The storage migration must not mutate catalog indexes. Older worktree
    # variants attempted to drop unrelated indexes here, which made upgrades
    # non-repeatable and broke rollback safety.

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pi_tag_deletion_jobs')
    op.drop_table('pi_ingestion_state')
    with op.batch_alter_table('pi_ingestion_coverage', schema=None) as batch_op:
        batch_op.drop_index('ix_pi_ingestion_coverage_tag_range')

    op.drop_table('pi_ingestion_coverage')
    op.drop_table('pi_backfill_jobs')
    with op.batch_alter_table('pi_samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pi_samples_ts'))
        batch_op.drop_index(batch_op.f('ix_pi_samples_tag_id'))

    op.drop_table('pi_samples')
    # ### end Alembic commands ###
