"""Core package."""
from app.core.config import settings, get_settings
from app.core.logging import configure_logging, logger
from app.core.exceptions import (
    AppError,
    NotFoundError,
    DuplicateCodeError,
    DuplicateTagError,
    InvalidEquipmentError,
    InvalidSectionError,
    SectionNotBelongsToEquipmentError,
    InvalidVariableTypeError,
    DependencyExistsError,
    ValidationError,
    TagInactiveError,
    TimeRangeInvalidError,
    QueryLimitExceededError,
    PiNotConfiguredError,
    PiAuthError,
    PiTimeoutError,
    PiSSLError,
    PiUnavailableError,
    PiInvalidResponseError,
    PiTagNotFoundError,
    PiUnsupportedAuthError,
)

__all__ = [
    "settings",
    "get_settings",
    "configure_logging",
    "logger",
    "AppError",
    "NotFoundError",
    "DuplicateCodeError",
    "DuplicateTagError",
    "InvalidEquipmentError",
    "InvalidSectionError",
    "SectionNotBelongsToEquipmentError",
    "InvalidVariableTypeError",
    "DependencyExistsError",
    "ValidationError",
    "TagInactiveError",
    "TimeRangeInvalidError",
    "QueryLimitExceededError",
    "PiNotConfiguredError",
    "PiAuthError",
    "PiTimeoutError",
    "PiSSLError",
    "PiUnavailableError",
    "PiInvalidResponseError",
    "PiTagNotFoundError",
    "PiUnsupportedAuthError",
]
